// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1280","screenHeight":"720","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"Resolucion","status":true,"description":"Cambia la resolución del juego.","parameters":{"Ancho":"1280","Alto":"720"}},
{"name":"PantallaCompleta","status":true,"description":"Pantalla completa en celular al primer toque (sin bloqueo de orientacion).","parameters":{}},
{"name":"PantallaVertical","status":true,"description":"En celular vertical, el juego cubre toda la pantalla y la cámara sigue al personaje.","parameters":{}},
{"name":"CustomLogo","status":true,"description":"Shows RPG Maker and user logos at the start of the game.","parameters":{"logo1":"","logo1ImageName":"","logo1Skippable":"true","logo1Coordinate":"","logo1X":"408","logo1Y":"312","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"AbrirUrl","status":true,"description":"Sin título. Ir a la página (guarda y redirige) y volver cargando la partida.","parameters":{"PaginaCine":"verdad-o-reto.html"}},
{"name":"OnlineFirebase","status":true,"description":"Multijugador Firebase v2: nombres, movimiento suave, chat e idioma guardado.","parameters":{"databaseURL":"https://verdadreto-6bb8d-default-rtdb.firebaseio.com","IdiomaVariable":"1","MostrarMiNombre":"true","TraductorURL":"https://verdadreto-traductor.adhlyrics.workers.dev"}}
];
